version: "3.9"
x-container-port: 3000
x-external-host-names:
  - grafana.internal.example.com
networks:
  internal:
    external: true
    name: internal
  monitoring:
    external: true
    name: monitoring
services:
  application:
    image: grafana/grafana:11.2.0
    hostname: monitoring_grafana
    container_name: monitoring_grafana
    networks:
      - monitoring
      - internal
    user: "1000:1000"
    volumes:
      - type: bind
        source: ${DATA_BASE_PATH}/grafana
        target: /var/lib/grafana
