networks:
  internal:
    external: true
    name: internal
  postgres:
    external: true
    name: postgres
services:
  application:
    image: postgres:17.6
    hostname: postgres
    container_name: postgres
    networks:
      - internal
      - postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: ${DATA_BASE_PATH}/postgres/17/data
        target: /var/lib/postgresql/data
