networks:
  internal:
    external: true
    name: internal
  main:
    external: true
    name: main
services:
  haproxy_public:
    image: haproxy:3.1.5-alpine
    hostname: haproxy-public
    container_name: proxy_public
    networks:
      - main
    ports:
      - "${PUBLIC_IP}:${PUBLIC_PORT_HTTP}:80"
      - "${PUBLIC_IP}:${PUBLIC_PORT_HTTPS}:443"
    ulimits:
      nofile: 10240
    volumes:
      - type: bind
        source: ${DATA_BASE_PATH}/haproxy-public
        target: /usr/local/etc/haproxy
        read_only: true
      - type: bind
        source: ${DATA_BASE_PATH}/haproxy-public-ssl
        target: /usr/local/etc/ssl/certs
        read_only: true
      - type: bind
        source: ${DATA_BASE_PATH}/haproxy-public-stats
        target: /var/lib/haproxy-socket
        read_only: false
    profiles:
      - public
  haproxy_internal:
    image: haproxy:3.1.5-alpine
    hostname: haproxy-internal
    container_name: proxy_internal
    networks:
      - internal
    ports:
      - "${PRIVATE_IP}:${PRIVATE_PORT_HTTP}:80"
      - "${PRIVATE_IP}:${PRIVATE_PORT_HTTPS}:443"
      - "${PRIVATE_IP}:5432:5432"
    ulimits:
      nofile: 10240
    volumes:
      - type: bind
        source: ${DATA_BASE_PATH}/haproxy-internal
        target: /usr/local/etc/haproxy
        read_only: true
      - type: bind
        source: ${DATA_BASE_PATH}/haproxy-internal-ssl
        target: /usr/local/etc/ssl/certs
        read_only: true
    profiles:
      - internal
