allowBuilds:
  esbuild: false

blockExoticSubdeps: true

dedupeInjectedDeps: true

linkWorkspacePackages: deep

minimumReleaseAge: 10080
minimumReleaseAgeExclude: []

strictPeerDependencies: true

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 10080
