name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    name: security-scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required to upload SARIF files.

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          minimum_release_age: 7d
          cache: true

      - name: Run zizmor scan
        uses: zizmorcore/zizmor-action@cc914d7f3750a2d13d75c7f184a1060aa0e9d482 # v0.6.4

      - name: Cache trivy database
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: /tmp/trivy-cache
          key: trivy-${{ runner.os }}-${{ runner.arch }}
          restore-keys: |
            trivy-${{ runner.os }}-${{ runner.arch }}-

      - name: Run trivy scan
        id: trivy-scan
        continue-on-error: true
        env:
          TRIVY_OUTPUT: '/code/trivy-results.sarif'
        run: mise run trivy

      - name: Upload trivy scan results to GitHub Security
        uses: github/codeql-action/upload-sarif@1c5b675653bb5c22dbe9b12b556ec555138e09fd # v4.38.1
        with:
          sarif_file: './trivy-results.sarif'

      - name: Fail if trivy-scan failed
        if: steps.trivy-scan.outcome == 'failure'
        run: exit 1

  build:
    name: build
    runs-on: ubuntu-latest

    needs:
      - security-scan

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c # v4.3.0
        with:
          minimum_release_age: 7d
          cache: true

      - run: pnpm ci

      - run: pnpm run build

      - run: pnpm run test:unit
        # TODO: figure out running e2e tests in ci
        # - run: pnpm run test:e2e

      - run: pnpm run lint:ci
